//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVIM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cos()
        {
            this.CosProdus = new HashSet<CosProdus>();
        }
    
        public int IdCos { get; set; }
        public int IdClient { get; set; }
        public int IdCodStatusCos { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual StatusCos StatusCos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CosProdus> CosProdus { get; set; }
    }
}
