//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVIM.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVIMEntities : DbContext
    {
        public MVIMEntities()
            : base("name=MVIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresa> Adresa { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<CategorieProdus> CategorieProdus { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Comanda> Comanda { get; set; }
        public virtual DbSet<ComandaProdus> ComandaProdus { get; set; }
        public virtual DbSet<Cos> Cos { get; set; }
        public virtual DbSet<PozaProdus> PozaProdus { get; set; }
        public virtual DbSet<Producator> Producator { get; set; }
        public virtual DbSet<Produs> Produs { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<StatusComanda> StatusComanda { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
